server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lcwd_userservice
    username: root
    password: ronit
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:




#        dialect: org.hibernate.dialect.MySQLDialect

# Logging configuration
#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
